<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Page</title>
    
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    
    <!-- Material Symbols -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" 
    rel="stylesheet">
    
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
    
    <!-- Optional custom CSS -->
    <link href="{{ asset('css/report-custom.css') }}" rel="stylesheet">
</head>
<body class="bg-gray-200">

<div class="report-page min-h-screen flex flex-col bg-grey-200 text-black text-lg">

    <!-- HEADER -->
    <header class="bg-white shadow-sm">
        <div class="container mx-auto flex flex-col md:flex-row justify-between items-center p-4 gap-4">
            <h2 class="text-blue-900 text-2xl font-bold">DIGIVOTE</h2>
            <div class="flex flex-col md:flex-row items-center gap-4 md:gap-6">
                <!-- NAVBAR -->
                                 <nav class="flex flex-wrap gap-4">                        
<a href="/Home" class="group relative text-black hover:text-blue-900 font-semibold">
                        Home
                            
<span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
                    </a>
                    <a href="/about Us" class="group relative text-black hover:text-blue-900 font-semibold">
                      about Us  
                        <span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
                    </a>
                    <a href="/contact us" class="group relative text-black hover:text-blue-900 font-semibold">
                        contact us
                        <span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
                    </a>
                    <a href="/candidate" class="group relative text-black hover:text-blue-900 font-semibold">
                        candidate
                        <span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
                    </a>                 
                       <a href="/" class="group relative text-black hover:text-blue-900 font-semibold">
                    election                       
                     <span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
                                        </a>                        
                     <a href="/" class="group relative text-black hover:text-blue-900 font-semibold">
voter

<span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
</a>
<a href="/" class="group relative text-black hover:text-blue-900 font-semibold">
result

<span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
</a>
<a href="/" class="group relative text-black hover:text-blue-900 font-semibold">
login/register
<span class="absolute left-0 -bottom-1 w-0 h-0.5 bg-blue-900 transition-all group-hover:w-full"></span>
</a>
              </nav>
                <div class="flex items-center gap-2 text-black">
                    <span>Admin Nimra</span>
                     
                                         <span class="material-symbols-outlined text-blue-900 text-3xl">account_circle</span>
                </div>
            </div>
        </div>
    </header>

    <!-- PAGE TITLE -->
    <h1 class="text-black text-2xl md:text-3xl font-semibold text-center my-6">Report Page</h1>

    <!-- INFO BOXES -->
    <div class="container mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mb-6">
        <div class="bg-white shadow p-4 text-center rounded">
            <h3 class="text-blue-900 font-semibold text-lg">Election generated Date</h3>
            <p class="text-black mt-2">DD\MM\YEAR</p>
        </div>
        <div class="bg-white shadow p-4 text-center rounded">
            <h3 class="text-blue-900 font-semibold text-lg">Generated By</h3>
            <p class="text-black mt-2">Admin</p>
        </div>
        <div class="bg-white shadow p-4 text-center rounded">
            <h3 class="text-blue-900 font-semibold text-lg">Report Type</h3>
            <select class="mt-2 w-full border border-gray-300 rounded p-1">
                <option>General Summary</option>
                <option>Analytic Detail</option>
                <option>votes audit logs</option>
                 </select>
        </div>
    </div>

    <!-- REPORT TYPE BOXES -->
    <div class="container mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div class="bg-white shadow p-4 text-center rounded hover:scale-105 transition-transform cursor-pointer group report-card">
            <i class="fa-solid fa-users text-blue-900 text-3xl mb-2"></i>
            <h3 class="text-black-600 font-semibold">Voter Report</h3>
        </div>
        <div class="bg-white shadow p-4 text-center rounded hover:scale-105 transition-transform cursor-pointer group report-card">
            <i class="fa-solid fa-user-tie text-blue-900 text-3xl mb-2"></i>
            <h3 class="text-black-600 font-semibold">Candidate Report</h3>
        </div>
        <div class="bg-white shadow p-4 text-center rounded hover:scale-105 transition-transform cursor-pointer group report-card">
            <i class="fa-solid fa-chart-bar text-blue-900 text-3xl mb-2"></i>
            <h3 class="text-black-600 font-semibold">Voting Summary</h3>
        </div>
        <div class="bg-white shadow p-4 text-center rounded hover:scale-105 transition-transform cursor-pointer group report-card">
            <i class="fa-solid fa-vote-yea text-blue-900 text-3xl mb-2"></i>
            <h3 class="text-black-600 font-semibold">Final Result</h3>
        </div>
    </div>

    <!-- REPORT DISPLAY -->
    <h2 class="text-center text-gray-800 font-semibold text-xl md:text-2xl mb-4 mt-6">Report Display</h2>

    <div class="container mx-auto overflow-x-auto mb-6">
        <table class="min-w-full text-center border border-gray-300">
            <thead class="bg-blue-900 text-white">
                <tr>
                    <th class="p-2">Candidate NAME</th>
                    <th class="p-2">Symbol</th>
                    <th class="p-2">Party</th>
                    <th class="p-2">Votes COUNT</th>
                    <th class="p-2">Status</th>
                </tr>
            </thead>
            <tbody>
                <tr class="bg-white">
                    <td class="p-2">Ali Khan</td>                   
                     <td class="p-2 text-center text-blue-900">
    <span class="text-2xl">💎</span> <p class="text-[12px] font-extrabold mt-1"></p>
</td> 

                    <td class="p-2">Party A</td>
                    <td class="p-2">4200</td>
                    <td class="p-2 font-bold text-blue-900">Leading</td>
                </tr>
                <tr class="bg-gray-50">
                    <td class="p-2">Usman Tariq</td>                   
                     <td class="p-2 text-center text-blue-900">
    <span class="text-3xl">🚀</span> <p class="text-[12px] font-extrabold mt-1"></p>
</td>

                    <td class="p-2">Party B</td>
                    <td class="p-2">3500</td>
                    <td class="p-2 text-black">Running</td>
                </tr>
                <tr class="bg-white">
                    <td class="p-2">Ahmed Raza</td>
                    <td class="p-2 text-center text-blue-900">
                    <span class="text-5xl">⭐</span> <p class="text-[12px] font-extrabold mt-1"></p>
</td>

                    <td class="p-2">Party C</td>
                    <td class="p-2">2800</td>
                    <td class="p-2 text-black">Running</td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- DOWNLOAD BUTTON -->
    <div class="text-center mb-6">
        <button id="downloadReport" class="bg-blue-900 text-white px-6 py-2 rounded font-semibold hover:bg-white hover:text-blue-900 transition-colors">
            Download Report in pdf</i>
        </button>
    </div>

    <!-- FOOTER -->
    <footer class="bg-white mt-auto border-t py-4">
        <p class="text-center text-gray-600 mb-2">
            Copyright © 2026 Digital Online Election<br/>
            Developed by Nimra Arshad, Misbaah, Khansa
        </p>
        <div class="flex justify-center gap-4 text-blue-900">
            <span class="material-symbols-outlined cursor-pointer">share</span>
            <span class="material-symbols-outlined cursor-pointer">mail</span>
            <span class="material-symbols-outlined cursor-pointer">help</span>
        </div>
    </footer>

</div>

<script src="{{ asset('js/report.js') }}"></script>
</body>
</html>
